name: Ekstrak Zip Otomatis

on:
  workflow_dispatch:

# JALUR UTAMA UNTUK MEMBERI IZIN PUSH KODE
permissions:
  contents: write

jobs:
  unzip-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ekstrak proyek.zip
        run: |
          # Cek apakah file benar-benar ada sebelum diekstrak
          if [ -f "proyek.zip" ]; then
            unzip -o proyek.zip -d .
            rm proyek.zip
          else
            echo "File proyek.zip tidak ditemukan!"
            exit 1
          fi

      - name: Commit dan Push Perubahan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Menggunakan kondisi agar tidak error jika tidak ada perubahan baru
          git diff-index --quiet HEAD || git commit -m "Ekstrak proyek.zip otomatis"
          git push
